apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: calcback 
spec: 
  selector: 
    matchLabels: 
      slavetype: calcback 
  replicas: 10
  template: 
    metadata: 
      labels: 
        slavetype: calcback 
    spec: 
      containers: 
      - name: calcback
        image: docker.io/prryplatypus/calcback:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: "mariadb"
        - name: MYSQL_DATABASE
          value: "practica3"
        - name: MYSQL_USER
          value: "practica3"
        - name: MYSQL_PASSWORD
          value: "mgqiTocxedWO06PBUXlk"
        - name: RSA_PUB_KEY
          value: |-
            -----BEGIN PUBLIC KEY-----
            MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvJEYqr/kw4MA+G/JVYT7
            I8GELIDBl/YxjMUJwwXbMbJ0C+9iIVhc199NrH+FOVYSxG7rStVLx+X5HGX96nmN
            VjcpXi5yTcmnLMmFoXeUZnBL/JdgAOg3/Tri8SpThLB0K4+8jx1o+LTHDUmjZ/c5
            D0mEfoKUo2U1cTDcQvGLsKE+/4m55FamL/Ijj2lI9kxXmuRn0jFsyqj3N6V6DPUj
            N4o9tsA5VBeb3lsLW2IDaNKVLkgDBSME9F21JraRAeDIHERPY7VEPCdqQLpl603C
            QpP7uvx22Q1Uk9akgbbys5PjnoMDx9I6BMJ1Ylj/RLrD5QlsfXp7N1BjEHGboOL1
            Py14Wud4hlVYF8OhqLjV7Vws3HGC+2EUDQHL5fyNUKMrL/JuZeVI8KplC8mJ2T75
            JI9tznCmbJ/AwWmKEkZPJd3WC38h/Y/XtJ2tmFifBdBytK6Akn/F8UjOADgd3hXj
            FjTBH44jHmjErAZ/XuOumLkjiCpn9qdOCyezDLYDS2SpKoGQUEwOhF9X3K20cwYG
            vr0WOXIrU1a5gzL8AYISnKsN6DZpLnp2fyO67AdxnboLGVBDXksfFLXGGH5VulRx
            doN3OLnDO0w0whp6dXU9wEwhJua4oewn3BgEiLBLH9+a2urbRL7GRZXMPST7dv6b
            M4BIA0FItWtpDcjtvjjHstsCAwEAAQ==
            -----END PUBLIC KEY-----
        - name: RSA_PRIV_KEY
          value: |-
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEAvJEYqr/kw4MA+G/JVYT7I8GELIDBl/YxjMUJwwXbMbJ0C+9i
            IVhc199NrH+FOVYSxG7rStVLx+X5HGX96nmNVjcpXi5yTcmnLMmFoXeUZnBL/Jdg
            AOg3/Tri8SpThLB0K4+8jx1o+LTHDUmjZ/c5D0mEfoKUo2U1cTDcQvGLsKE+/4m5
            5FamL/Ijj2lI9kxXmuRn0jFsyqj3N6V6DPUjN4o9tsA5VBeb3lsLW2IDaNKVLkgD
            BSME9F21JraRAeDIHERPY7VEPCdqQLpl603CQpP7uvx22Q1Uk9akgbbys5PjnoMD
            x9I6BMJ1Ylj/RLrD5QlsfXp7N1BjEHGboOL1Py14Wud4hlVYF8OhqLjV7Vws3HGC
            +2EUDQHL5fyNUKMrL/JuZeVI8KplC8mJ2T75JI9tznCmbJ/AwWmKEkZPJd3WC38h
            /Y/XtJ2tmFifBdBytK6Akn/F8UjOADgd3hXjFjTBH44jHmjErAZ/XuOumLkjiCpn
            9qdOCyezDLYDS2SpKoGQUEwOhF9X3K20cwYGvr0WOXIrU1a5gzL8AYISnKsN6DZp
            Lnp2fyO67AdxnboLGVBDXksfFLXGGH5VulRxdoN3OLnDO0w0whp6dXU9wEwhJua4
            oewn3BgEiLBLH9+a2urbRL7GRZXMPST7dv6bM4BIA0FItWtpDcjtvjjHstsCAwEA
            AQKCAgBcPTWtwLRsltaQsE3yEVyv/udixZDtfrZ6P6Aoz+KLCtoNRInh+dFgn5Dl
            QnOuulXv1LowHuo03F/g7lsoqVDjzZPkyB+NwYiPNfyyIUZsXZ4t7vY9O1q3+mgs
            xCGalJ4e+O6pqx9AGV4NN+pA3wQAYFv5bnK7ArUDq3zzGijUu+uPIJXYBjLA3Vdb
            vYq9QFbSI8xNW3P2JnTXuZBcakVR08Ogc6MXaX0LZcnGZ8l3KxtiSkN/7cNsrbIB
            P+jq3EPG3/tdsLuyGS22f/d/BMhzvOO0ce7I+eZXcvWBpjZOdZcwYLImusU6ssys
            0Q/9VMaicNuq/ZDsW9w5nPkd2CdSav9vD3EWFuC0H0DEr7wlgHtVQO5FT6bKxsxX
            sg2Mr+4ymtVKQ3vDg19faYTXzIf+O7yxsyUWskCjSabmpKEQxZWJ/rM39vbhxPwg
            SQ3MaikUQRlUxEfr0MH2UUQ6ikjqzL4FFQ6L4pqV1sxbMsVlHit1uydQYxEMjRr/
            VfdzCu6896hWipnIqrfcARxuKW4xC5BWaFQGJUbRDiTwBWaULxTS0HGVn40VPDO9
            9RN0pjF7Jf/uPCe7CeShNdCNrMWmBVwJGhbpPxsS58odB5TaUfNFk579UKOUAm3L
            syanodoRjHGJrMMkZiNheZxAjeyfPrupxx9l69ngSVkgoKeVUQKCAQEA5naIYS4o
            L+5iuvDIMsfMNNxEwvQ34+deFfhvut4Bot280JiBhvlFhobtqr9Iw7NoFvE/637F
            xzQCwb4Hl0+0EKAtmGImHPlRvVDIeCz0Uc4wf61hHq/UbPg8lX+jmQIoE0ijFFsI
            i+b+GFN7FO6Est338jIZQS+IGyiOQ8+T5kllBO2wtESIkqA5mMnwHFNah3jaEf6F
            hhYffGsfm0QZic2Q5yJ6dvZ47tfc9Yf7ISQuZ9nXJvo4Vymw8YfgmIw5p3XdipdQ
            JhySQou3mGS28lG736WGxJ7Y6sGbBSh1BhF+4i3UEDFsV8NE+rInbI9rZtgWM7yH
            199Xnc2lsjdRTQKCAQEA0XYbbOlMqHsjussBlGgRj5EykSikjbxW6HJ7VQw45sH8
            eZjn5E7gwwcwXjnrhYLyeI8ahg8W64dZpvcMptrcEVs+D6hTr6G9AIuIfiCKVP6C
            iVYTpO0Iz0R/t2yLSAC4S4gnvZ0VdEy4/LxIwGtmjOcw8oU2c1DW+cM8TWHpuDUA
            cuYA8ek6k++gMvxvy/GgeFzZiG9Bd4tFQ8AHFFnxXWPoz9Lxx9ey9IgiZ4WsrYUF
            M0q3xbkwv2XvNF/QZXMWFvAivddC5MUzgosPTTBqOY1NPAe2E5y3K6ZhDUI8Y9D6
            fp1zwxDWrT5ElCkgudo654lQ3aABeGOGEeE74yWAxwKCAQEA4XSaDH/sHp/WBE2j
            fFILSrclqZbiyljAqTumiie/cAX+Pg7DwDhBtM5w2TZSR+lN7gvK3WXis/MEs2Zk
            5Li7Tfx1PnreEEAzn8HUrARGa3UL6wvBVBTs+kGKezIn6Hq8m8jWiQZZgQvUDhY0
            9ZA1TwppEo3COQv32aG+M0ZxyLqKUdz5nhDhjpeiYP9En2FH0fn/U9Ur6LXhzYS6
            odloJnBszkDjj1eljPquFaEWoyBTKZNpsJ7e2R5XFKI5rOKZUGK0/WzzoqUWzHUE
            gdgdRUeCRNMY2WcQi/Ak6FHg0bPx7fCpYcIH3H+SDrKUcNaJWk4QwkIwnpXGkADr
            lUIajQKCAQBVrjJZwrUQ1g4vgosK4ecNCx/cMPve3oPOYcYBbBZ6ji9wrhNtWLao
            EHDAmoC1BHOazS7UV6fQgHUzzyrltfD/SIuCbCCPX2Gor2sN7NGpItLSytsOQ8eu
            wR5dMZFnyqOYggF/lpoIELo65+n6i/RO/uMO0V8MnKzTTgGExeCM8WFVnrAURIsp
            qIOnV4uDqTszAQgavyfQdq/Gnu5GbORGh2/cUzWDwb/6NxWbsxqHgDo4WQADaVV/
            dXr7uZXNad5HU8NiVIOQgPopFCkWMg/BqwNE4wKf0yM6P7zDZ6y8R+evk0ifKmwm
            Qapb0NcKLzKZM5pYjfMMA+n7tl6A8/5RAoIBAHiEclRLLrFQwMmoecoWu7pa4F0d
            Kqu/J+FPvHquuTuJzBVbBwudGuKJgtoZIZ8UYvn+Dc2qCJWocHvmp+URcHD5X3Bu
            Y7E6VMjg9l/bzogGK+1P6RioaKRbEd/HaCI1wVJ+us1q6nWRq5N1R7tnvzt0P+JW
            x4+JrutH34arR0w9jnwhDjv2x8C8oFuhjQfzlxoZHjU3qyQXaBeMWvzSVHcEdC76
            UWg5pCTYBBJbFOZ12CvI1/Avqoftybwh3s4MvABvdTFVUeQU8LJtkWTJVNtxJXMv
            z67fykhyINvmHptTJy+W57x+9gG5W8LEh7Vvl31DkCoxx5AAEIesaLq1t/c=
            -----END RSA PRIVATE KEY-----
