apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: multmatrix 
spec: 
  selector: 
    matchLabels: 
      slavetype: multmatrix 
  replicas: 10
  template: 
    metadata: 
      labels: 
        slavetype: multmatrix 
    spec: 
      containers: 
      - name: multmatrix
        image: docker.io/prryplatypus/multmatrix:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081